# Automatically generated by configure - do not modify
SRC_PATH=/home/heinzeen/Desktop/sanitizer/qmsan/qemu/roms/vgabios
AS=as
CCAS=clang
CC=clang
BCC=bcc
CPP=clang -E
OBJCOPY=objcopy
IASL=iasl
LD=ld
RANLIB=ranlib
